### PR TITLE
FINAL final, JSON updating but not replacing

### PR DESCRIPTION
**Pull request by ghost**
Seems they can't be automatically merged, if there's conflict, please paste this method to bottom of PlayerScene2.cs

void SetTopicTrue(string topic)
    {
        JSONNode json = JSON.Parse(playerJSON.text);
        json[0]["playerLearned"][0][topic].Value = "True";
        File.WriteAllText(Environment.CurrentDirectory + "/Assets/Resources/JSON/JSONPlayer.json", json.ToString());
    }

### CODE REVIEW

**Comment by SabiKov** [comment]
I'll paste into

**Comment by SabiKov** [comment]
screenshot 2015-12-04 12 44 58

**Comment by SabiKov** [comment]
It seems, exactly the same

**Comment by ghost** [comment]
Ok, sorry, must have checked before merging upstream/master
Thanks

**Pull request closed without merging**
